/**
 * Regenerates `.claude/context/file_map.md` from the source tree.
 *
 * A file's summary is its line in `file_map.overrides.json`, or, failing that,
 * the first sentence of the docblock that introduces it. The override wins so
 * a file whose header says something true but unhelpful out of context can be
 * described here instead of being re-commented. Anything with neither is
 * reported on stdout. Run after adding, moving or deleting a file:
 * `npm run context:map`.
 */

import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { join, relative, sep } from "node:path"

const ROOT = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")
const OUT = join(ROOT, ".claude/context/file_map.md")
const OVERRIDES = join(ROOT, ".claude/context/file_map.overrides.json")

const ROOTS = ["src", "server", "scripts"]
const EXTENSIONS = /\.(ts|tsx|mjs|css)$/
const SKIP = new Set(["node_modules", "dist", ".git", "server-data"])

const SECTIONS = [
  ["src/lib", "lib — domain rules, the HTTP client, pure helpers. No React."],
  ["src/mock", "mock — the stand-in backend. Runtime-agnostic."],
  ["server", "server — the mock's Node half, mounted on the Vite dev server."],
  ["src/hooks", "hooks — one hook per request a screen makes."],
  ["src/config", "config — static app configuration, no I/O."],
  ["src/pages", "pages — one per route."],
  ["src/components/layout", "components/layout — the app shell."],
  ["src/components/dashboard", "components/dashboard — home screen cards."],
  ["src/components/translations", "components/translations — the UI-key workspace."],
  ["src/components/templates", "components/templates — the message-template screen."],
  ["src/components/motion", "components/motion — animation primitives."],
  ["src/components/ui", "components/ui — shadcn/ui generated primitives. Regenerate, do not hand-edit."],
  ["src", "src — entry points and anything uncategorised."],
  ["scripts", "scripts — repo tooling."],
]

function walk(dir, found = []) {
  for (const entry of readdirSync(dir)) {
    if (SKIP.has(entry)) continue
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) walk(full, found)
    else if (EXTENSIONS.test(entry)) found.push(full)
  }
  return found
}

/**
 * Two places count as introducing a file: the very top, above the imports,
 * which is where a multi-export module states what it is; and directly above
 * the first export, which is where a one-export module does. Anything else is
 * documentation of a declaration — an exported type is usually a props bag —
 * and reads as a non-sequitur in the map.
 */
function summarise(file) {
  const head = readFileSync(file, "utf8").split("\n").slice(0, 120).join("\n")
  const body = head
    .replace(/^import\s[\s\S]*?from\s+["'][^"']+["'];?\s*$/gm, "")
    .replace(/^import\s+["'][^"']+["'];?\s*$/gm, "")
    .replace(/^\/\/.*$/gm, "")

  const block = fileHeader(head) ?? blockAboveFirstExport(body)
  if (block === null) return "—"

  const text = block
    .split("\n")
    .map((line) => line.replace(/^\s*\/?\*+\s?/, "").trimEnd())
    .join(" ")
    .replace(/\s+/g, " ")
    .trim()
  const sentence = text.split(/(?<=\.)\s/)[0] ?? text
  return sentence.length > 180 ? `${sentence.slice(0, 177)}…` : sentence
}

function fileHeader(head) {
  return head.startsWith("/**") ? head.slice(0, head.indexOf("*/")) : null
}

function blockAboveFirstExport(body) {
  const firstExport = body.search(/^export\s+(async\s+)?(function|const|default|class)\b/m)
  if (firstExport === -1) return null
  const before = body.slice(0, firstExport).trimEnd()
  if (!before.endsWith("*/")) return null
  const opened = before.lastIndexOf("/**")
  return opened === -1 ? null : before.slice(opened, before.length - 2)
}

const overrides = JSON.parse(readFileSync(OVERRIDES, "utf8"))

const files = ROOTS.flatMap((root) => {
  try {
    return walk(join(ROOT, root))
  } catch {
    return []
  }
}).map((full) => relative(ROOT, full).split(sep).join("/"))

const claimed = new Set()
const undescribed = []
const unusedOverrides = new Set(Object.keys(overrides).filter((key) => key !== "_readme"))
const lines = [
  "<!-- GENERATED by scripts/build_context_map.mjs — run `npm run context:map`. Do not edit by hand. -->",
  "",
  "# File map",
  "",
  "Every source file, one line each. Read this to choose what to open, instead",
  "of searching. The line is the file's own header docblock where it has one,",
  "and `file_map.overrides.json` where it does not.",
  "",
]

for (const [prefix, heading] of SECTIONS) {
  const group = files.filter((f) => f.startsWith(`${prefix}/`) && !claimed.has(f)).sort()
  if (group.length === 0) continue
  lines.push(`## ${heading}`, "")
  for (const f of group) {
    claimed.add(f)
    const described = overrides[f] ?? summarise(join(ROOT, f))
    unusedOverrides.delete(f)
    if (described === "—" && !f.startsWith("src/components/ui/")) undescribed.push(f)
    lines.push(`- \`${f}\` — ${described}`)
  }
  lines.push("")
}

writeFileSync(OUT, lines.join("\n"), "utf8")

console.log(`file_map.md: ${claimed.size} files, ${undescribed.length} undescribed`)
for (const f of undescribed) {
  console.log(`  undescribed: ${f} — add a header docblock, or a line in file_map.overrides.json`)
}
for (const f of unusedOverrides) {
  console.log(`  stale override: ${f} — no such file`)
}
